# Generated by Django 4.2.2 on 2023-07-23 05:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UtilisateurSimple',
            fields=[
                ('firebase_uid', models.CharField(max_length=150, primary_key=True, serialize=False)),
                ('image', models.ImageField(blank=True, null=True, upload_to='profile_images')),
                ('nom', models.CharField(max_length=32, null=True)),
                ('prenom', models.CharField(max_length=32, null=True)),
                ('email', models.EmailField(max_length=50, null=True)),
                ('date_inscription', models.DateTimeField(auto_now_add=True)),
                ('adresse', models.CharField(max_length=100, null=True)),
                ('role', models.CharField(default='Consommateur', max_length=30)),
                ('etat', models.CharField(max_length=30, null=True)),
                ('numero_telephone', models.IntegerField(null=True)),
                ('password', models.CharField(max_length=128, null=True)),
                ('confirm_password', models.CharField(max_length=128, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Commercant',
            fields=[
                ('utilisateursimple_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='user_auth.utilisateursimple')),
                ('description', models.TextField(null=True)),
            ],
            bases=('user_auth.utilisateursimple',),
        ),
        migrations.CreateModel(
            name='Consommateur',
            fields=[
                ('utilisateursimple_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='user_auth.utilisateursimple')),
            ],
            bases=('user_auth.utilisateursimple',),
        ),
        migrations.CreateModel(
            name='Livreur',
            fields=[
                ('utilisateursimple_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='user_auth.utilisateursimple')),
                ('vehicule', models.CharField(max_length=100, null=True)),
                ('horaire_de_travail', models.CharField(max_length=100, null=True)),
                ('zone_de_travail', models.CharField(max_length=100, null=True)),
                ('status', models.CharField(max_length=100, null=True)),
            ],
            bases=('user_auth.utilisateursimple',),
        ),
    ]
