# Generated by Django 4.1.10 on 2023-08-15 23:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0002_remove_notification_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='creator',
            field=models.IntegerField(null=True),
        ),
    ]
