# Generated by Django 4.1.10 on 2023-08-16 00:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0003_notification_creator'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notification',
            old_name='creator',
            new_name='creator_id',
        ),
    ]
