# Generated by Django 4.1.10 on 2023-08-16 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0004_rename_creator_notification_creator_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='creator_id',
            field=models.TextField(null=True),
        ),
    ]
