# Generated by Django 4.1.10 on 2023-08-16 00:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0005_alter_notification_creator_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notification',
            old_name='creator_id',
            new_name='creator_info',
        ),
    ]
