# Generated by Django 4.1.10 on 2023-08-16 09:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0016_delete_notification'),
        ('notification', '0006_rename_creator_id_notification_creator_info'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='event',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='event.eventdetails'),
        ),
    ]
