# Generated by Django 4.2.1 on 2023-08-01 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EventDetails',
            fields=[
                ('EventId', models.AutoField(primary_key=True, serialize=False)),
                ('EventName', models.CharField(max_length=500)),
                ('EventDescription', models.CharField(max_length=500)),
                ('EventImage', models.ImageField(max_length=500, upload_to='pictures/%Y/%M/%D/')),
                ('EventDate', models.DateField()),
            ],
        ),
    ]
