# Generated by Django 4.2.1 on 2023-08-01 19:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eventdetails',
            name='EventDate',
        ),
        migrations.RemoveField(
            model_name='eventdetails',
            name='EventImage',
        ),
    ]
