# Generated by Django 4.2.1 on 2023-08-02 00:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0003_eventdetails_eventimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventdetails',
            name='EventImage',
            field=models.ImageField(blank=True, upload_to='eventphoto/%y/%m/%d/'),
        ),
    ]
