# Generated by Django 4.2.1 on 2023-08-02 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0004_alter_eventdetails_eventimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventdetails',
            name='DateEvent',
            field=models.DateField(null=True),
        ),
    ]
