# Generated by Django 4.2.1 on 2023-08-02 11:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0005_eventdetails_dateevent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventdetails',
            name='DateEvent',
            field=models.DateField(blank=True, default=datetime.datetime(2023, 8, 2, 11, 55, 59, 415585, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
    ]
