# Generated by Django 4.2.1 on 2023-08-03 14:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0006_alter_eventdetails_dateevent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eventdetails',
            name='DateEvent',
        ),
        migrations.RemoveField(
            model_name='eventdetails',
            name='EventImage',
        ),
    ]
