# Generated by Django 4.2.1 on 2023-08-03 14:12

from django.db import migrations, models

import datetime
class Migration(migrations.Migration):

    dependencies = [
        ('event', '0007_remove_eventdetails_dateevent_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventdetails',
            name='DateEvent',
            field=models.DateField(blank=True, default=datetime.datetime(2023, 8, 2, 11, 55, 59, 415585, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
    ]
