# Generated by Django 4.2.1 on 2023-08-03 14:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0008_eventdetails_dateevent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eventdetails',
            name='DateEvent',
        ),
    ]
