# Generated by Django 4.2.1 on 2023-08-05 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0010_eventdetails_dateevent'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventdetails',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='event_images'),
        ),
        migrations.AlterField(
            model_name='eventdetails',
            name='DateEvent',
            field=models.DateField(blank=True, null=True),
        ),
    ]
