# Generated by Django 4.2.1 on 2023-08-05 15:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0011_eventdetails_image_alter_eventdetails_dateevent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eventdetails',
            name='image',
        ),
    ]
