# Generated by Django 4.1.10 on 2023-08-14 14:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_auth', '0001_initial'),
        ('event', '0013_eventdetails_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventdetails',
            name='creator',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='user_auth.commercant'),
        ),
    ]
