# Generated by Django 4.1.10 on 2023-08-15 22:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0015_notification'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Notification',
        ),
    ]
