# Generated by Django 4.1.10 on 2023-08-16 22:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user_auth', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('ReviewId', models.AutoField(primary_key=True, serialize=False)),
                ('ReviewRate', models.IntegerField(null=True)),
                ('ReviewContent', models.TextField(null=True)),
                ('DateReview', models.DateField(blank=True, null=True)),
                ('ConcernedProduct', models.CharField(max_length=500, null=True)),
                ('ConcernedVendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_auth.commercant')),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_auth.consommateur')),
            ],
        ),
    ]
