# Generated by Django 4.2.2 on 2023-07-22 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_admin', models.ImageField(blank=True, null=True, upload_to='profile_images')),
                ('nom_admin', models.CharField(max_length=32, null=True)),
                ('prenom_admin', models.CharField(max_length=32, null=True)),
                ('email_admin', models.EmailField(max_length=50)),
                ('password_admin', models.CharField(max_length=50)),
                ('date_inscription_admin', models.DateTimeField(auto_now_add=True)),
                ('numero_telephone_admin', models.IntegerField(null=True)),
                ('privilege', models.CharField(max_length=32, null=True)),
                ('equipe', models.CharField(max_length=32, null=True)),
            ],
        ),
    ]
